default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: <account>
      user: DBT_USER
      password: <password>
      role: DBT_ROLE
      database: ANALYTICS
      warehouse: TRANSFORM_WH
      schema: DBT_JPROVOST
      threads: 4