default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: pywkogy-ie46350
      user: DBT_USER
      password: wFt5$5^tHn28%g1
      role: DBT_ROLE
      database: ANALYTICS
      warehouse: TRANSFORM_WH
      schema: DBT_JPROVOST
      threads: 4